version: '3.9'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    networks:
      - s-network


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: prakhar
      POSTGRES_PASSWORD: GujratChas@123
      POSTGRES_DB: prakhar
    ports:
      - "5433:5432"
    networks:
      - s-network

    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  s-network:
    driver: bridge


volumes:
  postgres-s-data: